music/urls.py
from django.conf.urls import url
from . import views

app_name = "music"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^register/$', views.UserFormView.as_view(), name="register"),
    # /music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = "detail"),
    # music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name="album-add"),
    # music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album-update"),
    # music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name="album-delete"),

]

#BEFORE USIVG CLASS BASED VIEWS
# urlpatterns = [
#     url(r'^$', views.index, name="index"),
#     # /music/71/
#     url(r'^(?P<album_id>[0-9]+)/$', views.detail, name = "detail"),
#     # /music/<album_id>/favorite
#     url(r'^(?P<album_id>[0-9]+)favorite/$', views.favorite, name = "favorite"),
# ]

website/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length =250)
    album_title = models.CharField(max_length = 500)
    genre = models.CharField(max_length = 100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        '''When we create a new album, this function will redirect us to
        a newly created music.detail view with its new primary key'''
        return reverse('music:detail', kwargs={"pk":self.pk})

    def __str__(self):
        return self.artist + " - " + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length = 10)
    song_title = models.CharField(max_length = 250)
    is_favorite = models.BooleanField(default = False)
    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User

from django import forms

class UserForm(forms.ModelForm):
    ## widget=forms/Passworinput is for covering password with asterixes when typg password
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        ##Meta is basically information about your class
        model = User
        fields = ["username", "email", "password"]

music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic

from django.views.generic import View
from .models import Album
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    #to overwrite default 'object_list'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    ''' this form lets users to create new albums.
    When doinng new template for this view create a new html with lowercase name of model,
    underscore form, ex.: album_form'''
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    ##after deleting and album his command down below will redirect us to music:index page
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    ##form_class is the blueprnt for our form
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #displays a blank form, i.e. before filling the info, i.e first time
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
    ##processes form data, i.e. already filled data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            ##bellow code takes the data but dosnt save it to DB, but uses it locally
            user = form.save(commit=False)
            ## clean (normalized) data. Data formatted properly
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            ##bellow code sets users password
            user.set_password(password)
            ## finally save the user
            user.save()

            ##returns user objects if there s such a user and credentials are correct
            user = authenticate(username = username, password = password)

            if user is not None:
                ## before they login we need to check if they are active, , not banned or etc
                if user.is_active:
                    login(request, user)
                    ## we need to redirect them somewhere after their login is successful
                    return redirect('music:index')

        ##if their login is not successful, we will tell them to try again
        return render(request, self.template_name, {'form': form})














































#BEFORE USING CLAS BASED VIEWS

# from django.http import Http404
# #shorter and easier way of loading templates
# from django.shortcuts import render, get_object_or_404
# ##No need for httpresponse, sonce we are using render
# from django.http import HttpResponse
# #first way of loading templates
# # #from django.template import loader
# from .models import Album, Song
#
#
# def index(request):
#     all_albums = Album.objects.all()
#     context = {"all_albums": all_albums}
#     return render(request, 'music/index.html', context)
#     # template = loader.get_template('music/index.html')
#     # context = {"all_albums": all_albums,}
#     # return HttpResponse (template.render(context, request))
#
# def detail(request, album_id):
#     # try:
#     #     album = Album.objects.get(id=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("<-<-<- ___ Album does not exist ! ! ! ___ ->->->")
#     ## following line is a shorter way of dispyaing 404
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {"album": album})
#
#
# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#             'album': album,
#             'error_message': "!!! You did not select a valid song"
#         })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {"album": album})
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
    <div class="col-sm-12 col-md-7">
        <div class="panel-body">
            <h3>Create a new Album</h3>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'music/form-template.html' %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit
                        </button>

                    </div>

                </div>

            </form>
        </div>
    </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TNB Music{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}"> TNB Music</a>
        </div>

        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class=" ">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Detail{% endblock %}


{% block body %}

    <img src="{{album.album_logo.url}}", width=250>
    <h1>{{ album.album_title }}
    </h1>
    <h3>{{ album.artist }}
    </h3>

    {% for song in album.song_set.all %}
            {{ song.song_title }}
                {% if song.is_favorite %}
                    <img src="http://i.imgur.com/b9b13Rd.png">
                {% endif %}
        <br>
    {% endfor %}

{% endblock %}



{##BEFoRE USING CLASS BASED VIEWS#}
{#{% block body %}#}
{#    <img src="{{album.album_logo}}", width=250>#}
{#    <h1>{{ album.album_title }}#}
{#    </h1>#}
{#    <h3>{{ album.artist }}#}
{#    </h3>#}
{##}
{#    {% if error_message %}#}
{#        <p><strong>{{ error_message }} </strong> </p>#}
{#    {% endif %}#}
{##}
{#    <form action="{% url 'music:favorite' album.id %}" method="post">#}
{#        {% csrf_token %}#}
{#        {% for song in album.song_set.all %}#}
{#            <input type="radio" id="song{{ forloop.counter }}" name = "song" value ="{{ song.id }}"/>#}
{#            <label for="song{{ forloop.counter }}">#}
{#                {{ song.song_title }}#}
{#                    {% if song.is_favorite %}#}
{#                        <img src="http://i.imgur.com/b9b13Rd.png">#}
{#                    {% endif %}#}
{#            </label><br>#}
{#        {% endfor %}#}
{#        <input type="submit" value="Favorite">#}
{#    </form>#}
{#    <!-- <ul>#}
{#        {% for song in album.song_set.all %}#}
{#        <li>{{ song.song_title }} - {{ song.file_type }}#}
{#        </li>#}
{#        {% endfor %}#}
{#    </ul> -->#}
{#{% endblock %}#}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10"> {{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
        <ul>
            {% for album in all_albums %}
            {% comment %} this is hard coded url: <li><a href="/music/{{ album.id }}">{{album.album_title}}</a> {% endcomment %}
            <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        </ul>
{% endblock %}

{#{% block body %}#}
{#    {% if all_albums %}#}
{#    <h2>Here are all my albums</h2>#}
{#        <ul>#}
{#            {% for album in all_albums %}#}
{#            {% comment %} this is hard coded url: <li><a href="/music/{{ album.id }}">{{album.album_title}}</a> {% endcomment %}#}
{#            <li><a href ="{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% else %}#}
{#        <h3>You dont have any albums</h3>#}
{#    {% endif %}#}
{#{% endblock %}#}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
    <div class="container-fluid">
    <div class="col-sm-12 col-md-7">
        <div class="panel-body">
            <h3>Create a new Account</h3>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'music/form-template.html' %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit
                        </button>

                    </div>

                </div>

            </form>
        </div>
    </div>
    </div>
{% endblock %}